apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: ke5lfoc62-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:5453055b03d29882c0dc773ba9d1f53cfeb6eb2b@sha256:c86a2162d8ab794ba3cf09ce9868058bb67e7158c5d0f90b0dabceca48508e07
          name: container-image
